export const serverPlans = [
  {
    id: 1,
    name: "Essential Series",
    description: "Ideal for development & staging",
    cpu: "Intel Xeon E-2276G",
    ram:"32",
    storage:"500",
    network:"1",
    ramtext: "32 GB DDR4 ECC",
    storagetext: "2x 500GB SSD NVMe",
    networktext: "1 Gbps Unmetered",
    price: 149,
    featured: false,
  },
  {
    id: 2,
    name: "Business Series",
    description: "Production ready enterprise workloads",
    cpu: "Dual Intel Scalable 4210",
    ram:"128",
    storage:"2000",
    network:"10",
    ramtext: "128 GB DDR4 ECC",
    storagetext: "2x 2TB SSD NVMe (RAID 1)",
    networktext: "10 Gbps Burst",
    price: 389,
    featured: true,
  },
  {
    id: 3,
    name: "Enterprise Series",
    description: "High-performance database & virtualization",
    cpu: "AMD EPYC™ 7543",
    ram:"512",
    storage:"4000",
    network:"25",
    ramtext: "512 GB DDR4 ECC",
    storagetext: "4x 3.84TB SSD NVMe",
    networktext: "25 Gbps Dedicated",
    price: 899,
    featured: false,
  },
];