export const serverPlans = [
  {
    id: 1,
    name: "Essential Series",
    description: "Ideal for development & staging",
    cpu: "Intel Xeon E-2276G",
    ram: "32 GB DDR4 ECC",
    storage: "2x 500GB SSD NVMe",
    network: "1 Gbps Unmetered",
    price: 149,
    featured: false,
  },
  {
    id: 2,
    name: "Business Series",
    description: "Production ready enterprise workloads",
    cpu: "Dual Intel Scalable 4210",
    ram: "128 GB DDR4 ECC",
    storage: "2x 2TB SSD NVMe (RAID 1)",
    network: "10 Gbps Burst",
    price: 389,
    featured: true,
  },
  {
    id: 3,
    name: "Enterprise Series",
    description: "High-performance database & virtualization",
    cpu: "AMD EPYC™ 7543",
    ram: "512 GB DDR4 ECC",
    storage: "4x 3.84TB SSD NVMe",
    network: "25 Gbps Dedicated",
    price: 899,
    featured: false,
  },
];