export const pricingPlans = [
  {
    id: 1,
    title: "Starter",
    subtitle: "Best for small projects",
    monthlyPrice: 12,
    yearlyPrice: 9,
    features: [
      "2 vCPU Cores",
      "6 GB RAM",
      "100 GB NVMe SSD",
      "1 TB Bandwidth",
    ],
    button: "Configure Plan",
    popular: false,
  },
  {
    id: 2,
    title: "Business",
    subtitle: "Optimized for growth",
    monthlyPrice: 28,
    yearlyPrice: 21,
    features: [
      "4 vCPU Cores",
      "12 GB RAM",
      "250 GB NVMe SSD",
      "3 TB Bandwidth",
    ],
    button: "Deploy Now",
    popular: true,
  },
  {
    id: 3,
    title: "Professional",
    subtitle: "For high-traffic apps",
    monthlyPrice: 56,
    yearlyPrice: 42,
    features: [
      "8 vCPU Cores",
      "24 GB RAM",
      "500 GB NVMe SSD",
      "5 TB Bandwidth",
    ],
    button: "Configure Plan",
    popular: false,
  },
  {
    id: 4,
    title: "Enterprise",
    subtitle: "Maximum dedicated power",
    monthlyPrice: 112,
    yearlyPrice: 84,
    features: [
      "16 vCPU Cores",
      "48 GB RAM",
      "800 GB NVMe SSD",
      "10 TB Bandwidth",
    ],
    button: "Contact Enterprise",
    popular: false,
  },
];